premium-permission: exanthiax.pass.premium # The permission to access the premium tiers
gui-cache-ttl: 1000

battlepass-gui:
  title: "XBattlePass"
  mask:
    materials:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "111010111"
      - "111111111"
  buttons:
    tiers:
      item: lime_stained_glass_pane
      name: "&aTiers"
      lore:
        - ""
        - "&aLeft click &7to see"
        - "&7your battlepass progression"
        - "&7and claim rewards"
        - ""
      location:
        row: 2
        column: 4
    quests:
      item: orange_stained_glass_pane
      name: "&6Quests"
      lore:
        - ""
        - "&6Left click &7to see"
        - "&7all available quests"
        - "&7and your progression"
        - ""
      location:
        row: 2
        column: 6


tiers-gui:
  title: "XBattlePass: Tiers"
  mask:
    materials:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
    progression-pattern:
      - "109ab0jkl"
      - "2080c0i0m"
      - "3070d0h0n"
      - "4560efg0o"
      - "00000000p"
      - "00000000q"

  buttons:
    item-amount: "%level%"

    prev-page:
      material: arrow
      name: "&fPrevious Page"
      location:
        row: 6
        column: 4

    next-page:
      material: arrow
      name: "&fNext Page"
      location:
        row: 6
        column: 6

    close:
      material: barrier
      name: "&cClose"
      location:
        row: 6
        column: 5

    free-rewards-format: "&2%reward%"
    premium-rewards-format: "&9%reward%"
    empty-rewards-format: "&cNone"

    unlocked:
      item: lime_stained_glass_pane
      name: "&aTier %tier_numeral%"
      lore:
        - "&7Rewards:"
        - " &7* Free:"
        - "   &7%free-rewards%"
        - " &7* Premium:"
        - "   &7%premium-rewards%"
        - ""
        - "&aCLAIM"

    in-progress:
      item: yellow_stained_glass_pane
      name: "&eTier %tier_numeral%"
      lore:
        - "&7Rewards:"
        - " &7* Free:"
        - "   &7%free-rewards%"
        - " &7* Premium:"
        - "   &7%premium-rewards%"
        - ""
        - "&fProgress:"
        - "&8» &e%percentage_progress%%"
        - "&8» &e%current_xp%&8/&7%required_xp% &fXP"

    locked:
      item: red_stained_glass_pane
      name: "&cTier %tier_numeral%"
      lore:
        - "&cLOCKED"

    claimed:
      item: green_stained_glass_pane glint
      name: "&aTier %tier_numeral%"
      lore:
        - "&7Rewards:"
        - " &7* Free:"
        - "   &7%free-rewards%"
        - " &7* Premium:"
        - "   &7%premium-rewards%"
        - ""
        - "&aCLAIMED"

    # Custom GUI slots; see here for a how-to: https://plugins.auxilor.io/all-plugins/custom-gui-slots
    custom-slots: [ ]

categories-gui:
  title: "&8Categories: %page%"
  mask:
    materials:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "1c1c1c1c1"
      - "111111111"
  next-page:
    item:
      active: orange_stained_glass_pane name:"&aNext page"
      inactive: gray_stained_glass_pane name:"&7Next page"
    lore:
      active: [ ]
      inactive: [ ]
    row: 3
    column: 6
  prev-page:
    item:
      active: orange_stained_glass_pane name:"&aPrevious page"
      inactive: gray_stained_glass_pane name:"&7Previous page"
    lore:
      active: [ ]
      inactive: [ ]
    row: 3
    column: 4


###################### THIS IS NEW ######################

quests-gui:
  title: "Quests of Category %category%: %page%"
  mask:
    materials:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "1q1q1q1q1"
      - "111111111"
  next-page:
    item:
      active: orange_stained_glass_pane name:"&aNext page"
      inactive: gray_stained_glass_pane name:"&7Next page"
    lore:
      active: [ ]
      inactive: [ ]
    row: 3
    column: 6
  prev-page:
    item:
      active: orange_stained_glass_pane name:"&aPrevious page"
      inactive: gray_stained_glass_pane name:"&7Previous page"
    lore:
      active: [ ]
      inactive: [ ]
    row: 3
    column: 4

quests-icon:
  timer-format:
    start: "Starts in %time%"
    end: "Ends in %time%"
    reset: "Resets in %time%"
    none: "One-Time quest (does not end or reset)"
  tasks-format:
    - "&a* %task_name%"
    - "  %task_lore%"
  tasks-separator: []
  name: "&6%quest_name%"
  lore:
    - "&7%quest_description%" # This shows the description of the quest
    - ""
    - "&a%quest_tasks%" # This shows the tasks and their progress
    - "&7%quest_tier%" # Premium or Both
    - "&7%quest_timer%" # This shows either: When it unlocks, when it started, or the time until it resets.

time-format:
  split: " "
  days: "&6%value%&fd"
  hours: "&6%value%&fh"
  minutes: "&6%value%&fm"
  seconds: "&6%value%&fs"

sound:
  tier-up:
    enabled: true
    sound: block.anvil.use
    volume: 1
    pitch: 1
  reward-claim:
    enabled: true
    sound: block.anvil.use
    volume: 1
    pitch: 1
  quest-complete:
    enabled: true
    sound: block.anvil.use
    volume: 1
    pitch: 1